// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Nl_fhirML.Model
{
    public class ModelInput
    {
        [ColumnName("type"), LoadColumn(0)]
        public string Type { get; set; }


        [ColumnName("text"), LoadColumn(1)]
        public string Text { get; set; }


    }
}
